 se genera csv con informacion por id de funciones 
 ExecutionTimeDays: el tiempo promedio de execucion durante los 14 dias 
 InvocationsDays: numero de invocaciones promedio durante los 14 dias

los resultados de este procesamiento son usados en KMeans.ipynb

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
def invoc_per_func(ruta = Path.cwd()):
    return  [arch.name for arch in Path(ruta).glob('invocations_per_function_md.anon.d[01][0-9].csv')]

def function_duration(ruta = Path.cwd()):
    return  [arch.name for arch in Path(ruta).glob('function_durations_percentiles.anon.d[01][0-9].csv')]

In [3]:
invoc_func = invoc_per_func() 
invoc_per_func= pd.DataFrame()

f_durat = function_duration()
funt_duration= pd.DataFrame()

In [4]:
# recorremos archivos function_durations_percentiles para sacar la duracion promedio de cada funcion 
# y luego obtener un promedio general en de los 14 dias 
cont_arch = 1
funt_duration = pd.read_csv("function_durations_percentiles.anon.d01.csv", 
                            usecols=("HashFunction", "Average"))

for arch in f_durat:
    if(arch == "function_durations_percentiles.anon.d01.csv"):
        continue
    else:
        aux = pd.read_csv(arch, usecols =("HashFunction", "Average"))
        funt_duration = funt_duration.merge(aux, on=['HashFunction'], how='outer',suffixes=("_"+str(cont_arch), "_"+str(cont_arch+1)))
        cont_arch+=1
        aux = pd.DataFrame()

cont_arch = 1

funt_duration["ExecutionTimeDays"] = funt_duration.iloc[:, 1:].mean(axis =1)
funt_duration = funt_duration[["HashFunction", "ExecutionTimeDays"]]
funt_duration

,HashFunction,Average_1,Average_2,Average_3,Average_4,Average_5,Average_6,Average_7,Average_8,Average_9,Average_10,Average_11,Average_12,Average_13,Average_14
0,c968871b4ef0123401975d026b85cae2ad7dad9d06ae94...,100.0,92.0,76.0,79.0,59.0,89.0,86.0,90.0,94.0,91.0,52.0,97.0,93.0,64.0
1,1bc2d86badd21b18a8533d8e961e52585e5ad1fee0e2c2...,202.0,198.0,192.0,170.0,156.0,183.0,188.0,190.0,192.0,212.0,124.0,194.0,189.0,127.0
2,b4d7cb9985cd8c1b7fe5ef888bbde1883929e9a5b5d2a6...,11.0,14.0,12.0,12.0,20.0,29.0,126.0,12.0,13.0,16.0,35.0,14.0,14.0,93.0
3,ff612aae7b380ef81ccef063ff814354ee16018af65dc1...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,ee79840da82525548358f4b91d9fa1e550ec7af36bbe3e...,389.0,341.0,367.0,359.0,403.0,410.0,362.0,399.0,356.0,351.0,344.0,375.0,378.0,313.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82490,4795a4eddf26cca87a5c7c1de760fc1beefd16f866c197...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.0
82491,75e947006f189b6cce5c6516975142f29a0f169e764fde...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11966.0
82492,42212390028151a3ab9918fd440633957a4b3b8bd3e679...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1128.0
82493,11b3d8753f8f707b77c23063fb9cc9cfe9c74b40f9ab8c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1847.0
82494,de0430c3dca45b4ea0cf28d1882c911848eb830da28f19...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1169.0

In [8]:
# recorre invocations_per_function_md.anon para saber el promedio de veces que se invoca cada funcion en los 14 dias 
invoc_per_func = pd.read_csv("invocations_per_function_md.anon.d01.csv")
#dfaux = dfaux. drop(["HashOwner"], axis = 1)
cont_arch = 1
for arch in invoc_func:
    if(arch == "invocations_per_function_md.anon.d01.csv"):
        invoc_per_func["ivocationDay"] = invoc_per_func.iloc[:, 4:].sum(axis=1)
        invoc_per_func = invoc_per_func[["HashFunction", "Trigger", "ivocationDay"]]
        continue                                           
    else:
        aux = pd.read_csv(arch)
        aux["ivocationDay"] = aux.iloc[:, 4:].sum(axis=1)
        aux = aux[["HashFunction", "Trigger", "ivocationDay"]]
        
        invoc_per_func = invoc_per_func.merge(aux, on=['HashFunction','Trigger'], how='outer',suffixes=("_"+str(cont_arch), "_"+str(cont_arch+1)))
        print("van procesadas " + str(cont_arch))
        cont_arch+=1
        aux = pd.DataFrame()
        

invoc_per_func["InvocationsDays"] = invoc_per_func.iloc[:, 2:].mean(axis =1)
invoc_per_func = invoc_per_func[["HashFunction", "Trigger", "InvocationsDays"]]
invoc_per_func

invoc_per_func

van procesadas 1
van procesadas 2
van procesadas 3
van procesadas 4
van procesadas 5
van procesadas 6
van procesadas 7
van procesadas 8
van procesadas 9
van procesadas 10
van procesadas 11
van procesadas 12
van procesadas 13

,HashFunction,Trigger,ivocationDay_1,ivocationDay_2,ivocationDay_3,ivocationDay_4,ivocationDay_5,ivocationDay_6,ivocationDay_7,ivocationDay_8,ivocationDay_9,ivocationDay_10,ivocationDay_11,ivocationDay_12,ivocationDay_13,ivocationDay_14
0,520dbd6bd906840012aa0c4b778743efc7c0ac7b7caf96...,http,288.0,288.0,287.0,288.0,288.0,288.0,288.0,289.0,288.0,289.0,288.0,288.0,288.0,288.0
1,115ca7a2b5bc290052c3da74cd0347d19c3c67b7d5aa66...,http,288.0,288.0,287.0,288.0,288.0,288.0,287.0,288.0,288.0,288.0,288.0,288.0,288.0,288.0
2,93e6c664773bbec3a7f50a0e92fa7e97401a802dc6eed8...,orchestration,10.0,6.0,7.0,26.0,21.0,4.0,2.0,9.0,1.0,8.0,6.0,1.0,2.0,NaN
3,740c5c767e4b9978ee59a97d1829cfbaf755a47806a311...,http,11.0,6.0,7.0,22.0,23.0,1.0,3.0,11.0,3.0,3.0,2.0,NaN,NaN,NaN
4,c108b4864b866b38b80d0e4594cc6d038f39668b804a1b...,http,9.0,7.0,9.0,27.0,14.0,6.0,3.0,16.0,1.0,2.0,8.0,3.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74342,4795a4eddf26cca87a5c7c1de760fc1beefd16f866c197...,http,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
74343,75e947006f189b6cce5c6516975142f29a0f169e764fde...,storage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
74344,11b3d8753f8f707b77c23063fb9cc9cfe9c74b40f9ab8c...,storage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
74345,42212390028151a3ab9918fd440633957a4b3b8bd3e679...,storage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
74346,55e76e10f7305ccd9b673695e9a9c00d6a2e7a532453d1...,http,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [11]:
# poner en columna el tipo de trigger de cada funcion 
copyinvoc = invoc_per_func.copy()
triggers= ["http","event","orchestration","queue","storage","timer","others"] 
for tr in triggers:
    copyinvoc[tr] = np.where(copyinvoc["Trigger"] == tr, 1 , 0)
copyinvoc.InvocationsDays = copyinvoc.InvocationsDays.astype(int)
copyinvoc =  copyinvoc.drop(['Trigger'], axis=1)
copyinvoc

,HashFunction,Trigger,InvocationsDays,http,event,orchestration,queue,storage,timer,others
0,520dbd6bd906840012aa0c4b778743efc7c0ac7b7caf96...,http,288,1,0,0,0,0,0,0
1,115ca7a2b5bc290052c3da74cd0347d19c3c67b7d5aa66...,http,287,1,0,0,0,0,0,0
2,93e6c664773bbec3a7f50a0e92fa7e97401a802dc6eed8...,orchestration,7,0,0,1,0,0,0,0
3,740c5c767e4b9978ee59a97d1829cfbaf755a47806a311...,http,8,1,0,0,0,0,0,0
4,c108b4864b866b38b80d0e4594cc6d038f39668b804a1b...,http,8,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
74342,4795a4eddf26cca87a5c7c1de760fc1beefd16f866c197...,http,1,1,0,0,0,0,0,0
74343,75e947006f189b6cce5c6516975142f29a0f169e764fde...,storage,2,0,0,0,0,1,0,0
74344,11b3d8753f8f707b77c23063fb9cc9cfe9c74b40f9ab8c...,storage,1,0,0,0,0,1,0,0
74345,42212390028151a3ab9918fd440633957a4b3b8bd3e679...,storage,2,0,0,0,0,1,0,0
74346,55e76e10f7305ccd9b673695e9a9c00d6a2e7a532453d1...,http,1,1,0,0,0,0,0,0

In [13]:
Final = pd.merge(funt_duration, copyinvoc, on='HashFunction', how='outer')
Final = Final.dropna().reset_index(drop = True)
Final

,HashFunction,ExecutionTimeDays,InvocationsDays,http,event,orchestration,queue,storage,timer,others
0,c968871b4ef0123401975d026b85cae2ad7dad9d06ae94...,83.000000,2881.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1bc2d86badd21b18a8533d8e961e52585e5ad1fee0e2c2...,179.785714,366.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,b4d7cb9985cd8c1b7fe5ef888bbde1883929e9a5b5d2a6...,30.071429,36416.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,ff612aae7b380ef81ccef063ff814354ee16018af65dc1...,0.000000,26238.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ee79840da82525548358f4b91d9fa1e550ec7af36bbe3e...,367.642857,288.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
85241,097ab75c08f0ca8b87227508d0ba1585a77b720f465e9f...,NaN,38.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
85242,e94b4adac87eea7ad4d36c0c363cddd215da250848f43c...,NaN,51.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
85243,9881e690dacf4a9531f36e9a976da5dbf1db8f8c8fa4ec...,NaN,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
85244,9e53d8c39ac8b2cbda72649275f0ea25a5ece31f30a535...,NaN,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
85245,2720c65156fa7a5836b0810be1b5c0838c97812fc65e51...,NaN,230.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [18]:
Final.to_csv('MatrizDataFuntions.csv', index = False)
# archivo con